import { createFileRoute } from "@tanstack/react-router";
import { Printer } from "lucide-react";
import { AppShell } from "@/components/kq/AppShell";
import { farmerNav } from "@/components/kq/navs";
import { PageTitle, RoleGuard, StatusBadge, downloadCSV } from "@/components/kq/common";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { formatDate } from "@/lib/kq/demo-data";
import { useKQ } from "@/lib/kq/store";

export const Route = createFileRoute("/farmer/history")({
  head: () => ({
    meta: [
      { title: "My Procurement History — KISANQUEUE" },
      {
        name: "description",
        content:
          "Download digital procurement receipts and review every completed procurement with quantity, grade and centre.",
      },
      { property: "og:title", content: "My Procurement History — KISANQUEUE" },
      {
        property: "og:description",
        content: "Completed procurements and digital receipts.",
      },
    ],
  }),
  component: () => (
    <RoleGuard role="farmer">
      <History />
    </RoleGuard>
  ),
});

function History() {
  const { session, records, appointments, products, centres, farmers } = useKQ();
  const farmerId = session!.farmerId!;
  const farmer = farmers.find((f) => f.id === farmerId)!;
  const mine = records.filter((r) => r.farmerId === farmerId);

  const rows = mine.map((r) => {
    const appt = appointments.find((a) => a.id === r.appointmentId);
    const product = products.find((p) => p.id === appt?.productId);
    const centre = centres.find((c) => c.id === appt?.centreId);
    return {
      Token: appt?.token ?? "-",
      Product: product?.name ?? "-",
      "Requested Qty (Qtl)": appt?.quantityQtl ?? 0,
      "Actual Qty (Qtl)": r.actualQuantityQtl,
      Centre: centre?.name ?? "-",
      Date: formatDate(r.date),
      Quality: r.grade,
      Status: "Completed",
    };
  });

  const printReceipt = (index: number) => {
    const row = rows[index];
    if (!row) return;
    const w = window.open("", "_blank", "width=720,height=900");
    if (!w) return;
    w.document.write(`
      <html><head><title>Procurement Receipt ${row["Token"]}</title>
      <style>body{font-family:system-ui;padding:32px;color:#14311f}
      h1{margin:0;font-size:20px}table{width:100%;border-collapse:collapse;margin-top:20px}
      td,th{border:1px solid #cbd8cd;padding:8px;text-align:left;font-size:14px}</style></head>
      <body><h1>KISANQUEUE — Digital Procurement Receipt</h1>
      <p>Farmer: <b>${farmer.name}</b> · Survey No: ${farmer.surveyNo} · Village: ${farmer.village}</p>
      <table>${Object.entries(row)
        .map(([k, v]) => `<tr><th>${k}</th><td>${v}</td></tr>`)
        .join("")}</table>
      <p style="margin-top:24px;font-size:12px;color:#5a6b5e">Simulated demo receipt generated by the KISANQUEUE prototype.</p>
      </body></html>`);
    w.document.close();
    w.print();
  };

  return (
    <AppShell nav={farmerNav} roleLabel="Farmer Portal">
      <PageTitle
        title="My Procurement History"
        description="All completed procurements with digital receipts"
        action={
          <Button
            variant="outline"
            onClick={() => downloadCSV("procurement-history.csv", rows)}
            disabled={rows.length === 0}
          >
            Export CSV
          </Button>
        }
      />
      <Card className="card-elevated">
        <CardContent className="overflow-x-auto p-0">
          <Table>
            <TableHeader>
              <TableRow>
                {[
                  "Token",
                  "Product",
                  "Requested",
                  "Actual",
                  "Centre",
                  "Date",
                  "Quality",
                  "Status",
                  "Receipt",
                ].map((h) => (
                  <TableHead key={h}>{h}</TableHead>
                ))}
              </TableRow>
            </TableHeader>
            <TableBody>
              {rows.length === 0 && (
                <TableRow>
                  <TableCell colSpan={9} className="py-10 text-center text-muted-foreground">
                    No completed procurements yet.
                  </TableCell>
                </TableRow>
              )}
              {rows.map((r, i) => (
                <TableRow key={r["Token"]}>
                  <TableCell className="font-semibold">{r["Token"]}</TableCell>
                  <TableCell>{r["Product"]}</TableCell>
                  <TableCell>{r["Requested Qty (Qtl)"]} Qtl</TableCell>
                  <TableCell>{r["Actual Qty (Qtl)"]} Qtl</TableCell>
                  <TableCell>{r["Centre"]}</TableCell>
                  <TableCell>{r["Date"]}</TableCell>
                  <TableCell>{r["Quality"]}</TableCell>
                  <TableCell><StatusBadge status="Completed" /></TableCell>
                  <TableCell>
                    <Button size="sm" variant="outline" className="gap-2" onClick={() => printReceipt(i)}>
                      <Printer className="size-4" /> Print
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </AppShell>
  );
}
